version: "3.8"
services: 
  go:
    build: ./go 
    ports:
      - 8080:8080
    tty: true 
    volumes:
      - ../hiyoko:/go/app
    depends_on:
      - db

  db:
    # image: mysql:5.7
    image: mariadb:10.5
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiyoko
      MYSQL_USER: hiyoko
      MYSQL_PASSWORD: hiyoko

  # phpmyadmin:
  #   image: phpmyadmin
  #   environment:
  #     PMA_HOST: "db"
  #     UPLOAD_LIMIT: 102400000
  #   ports:
  #     - 8888:80
  #   depends_on:
  #     - db

  #   mailhog:
  #     image: mailhog/mailhog
  #     ports:
  #       - "1025:1025"
  #       - "8025:8025"
